// Creates scenarios/<id>/ for every row in data/scenarios.csv and (re)writes
// its README.md from the CSV and the default goal's scores. summary.md,
// analysis.md and any other context files in the folder are left untouched.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { parseCsv } from "../src/lib/csv.js";

const root = new URL("../", import.meta.url);
const rows = parseCsv(readFileSync(new URL("data/scenarios.csv", root), "utf8"));
const goal = JSON.parse(readFileSync(new URL("goals/social-contract/goal.json", root), "utf8"));
const scores = parseCsv(readFileSync(new URL("goals/social-contract/scores.csv", root), "utf8"));
const atlas = JSON.parse(readFileSync(new URL("data/policy-atlas/policies.json", root), "utf8"));
const atlasTitle = Object.fromEntries(atlas.policies.map((p) => [p.slug, p.title]));
const scenarioPolicies = parseCsv(readFileSync(new URL("data/scenario-policies.csv", root), "utf8"));

const coord = (v) => (v === "" || v == null ? "—" : v);

for (const s of rows) {
  const dir = new URL(`scenarios/${s.id}/`, root);
  mkdirSync(dir, { recursive: true });
  const mine = scores.filter((r) => r.scenario === s.id && !r.policy);
  const scoreRows = goal.criteria
    .map((c) => {
      const r = mine.find((m) => m.criterion === c.id);
      return `| ${c.name} | ${r ? r.score : "—"} | ${r ? r.reason : ""} |`;
    })
    .join("\n");
  const tagged = scenarioPolicies.filter((r) => r.scenario === s.id);
  const policySection = tagged.length
    ? `\n## Policies from the atlas\n\n${tagged
        .map((r) => (r.policy ? `- **${atlasTitle[r.policy]}** (\`${r.policy}\`): ${r.evidence}` : `- None named. ${r.evidence}`))
        .join("\n")}\n`
    : "";
  const files = ["summary.md", "analysis.md"].filter((f) => existsSync(new URL(f, dir)));
  const md = `# ${s.title}

<!-- Generated by scripts/scenario-folders.mjs from data/scenarios.csv and
goals/social-contract/scores.csv. Edit those, then re-run
\`npm run scenarios:folders\`. Put hand-written context in other files. -->

| | |
| --- | --- |
| **Author** | ${s.author} |
| **Published** | ${s.date || s.year} |
| **Type** | ${s.type}${s.framework ? ` — ${s.framework}` : ""} |
| **Source** | ${s.url ? `<${s.url}>` : "Not public"} |
| **Tags** | ${s.tags || "—"} |
| **Policy stance** | ${s.policy || "—"} |
| **Likelihood** | ${s.likelihood ? `${s.likelihood} — ${s.likelihood_reason}` : "—"} |

${s.desc}

## Map position

| Axis pair | x | y |
| --- | --- | --- |
| Labor demand × gain distribution | ${coord(s.x_labor)} | ${coord(s.y_labor)} |
| Public finances × job quality | ${coord(s.x_fiscal)} | ${coord(s.y_fiscal)} |

## Social contract scores (draft)

| Promise | Score | Reason |
| --- | --- | --- |
${scoreRows}
${policySection}
## Files

${files.map((f) => `- [\`${f}\`](${f})`).join("\n") || "- (none yet)"}
`;
  writeFileSync(new URL("README.md", dir), md);
}
console.log(`Wrote README.md for ${rows.length} scenario folders.`);
